### PR TITLE
fix(ob_tran): handle o_proj=longlat forward/inverse properly

### LINKED ISSUE #536: ob_tran projection does not handle o_proj=longlat properly
The new `ob_tran` projection does not work as expected when going forward or backwards from `longlat` / `identity`. This is because of the conversion between degrees and radians at the boundary. A special case is required to undo that automatic boundary conversion if the inner projection is `longlat`/`identity`.

### PR DESCRIPTION
**Pull request by potion-cellar**
Fixes #536 and adds test cases for this.

### CODE REVIEW

**Review by ahocevar — APPROVED** [review]
Thanks, @potion-cellar

File: test/testData.js [hunk 1]
```diff
@@ -726,6 +726,42 @@ var testPoints = [
       xy: -4
     }
   },
+  {
+    code: '+proj=ob_tran +o_proj=eqearth +o_lat_p=85 +o_lon_p=10',
+    ll: [20, 11],
+    xy: [2841069.7339, 808313.2811],
+    acc: {
+      ll: 1,
+      xy: -4
```
Comment (ahocevar) [inline test/testData.js:735]: Why did I approve this? Note to self: the accuracy here allows pretty much any value.

Comment (ahocevar) [reply test/testData.js:735]: Anyway, ob_tran is fixed with #573.
